### ISSUE TITLE
Calling Post on Start Up

### ISSUE THREAD

**Issue by andrewgjohns** [tafax/angular-digest-auth#7]
Hi

I notice that when calling dgAuthService.start(); a post request is made to the login
login: {
            method: 'Post',
            url: '/api/signin'
}

I had expected this call would only be made on signin.submit();

Further I was wondering if you had a sample angularJS webapp that I could use to get started.
Thanks for your help

Andrew

**Comment by tafax** [comment]
The POST request is made after the start because the library needs to know the details of the server challenge used to create the authentication header. It is only possible by performing a request and parse the authentication header that a server, configured to use digest authentication, will send back.
This is a necessary step when you try to authenticate the user with the credentials stored in the local storage, previously submitted by himself in another session.
